[package]
name = "buildy"
version = "0.0.1"
authors = ["Steve Mostovoy <stevemostovoysm@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
crossbeam = "0.7.2"
duct = "0.13.1"
walkdir = "2"
rust-crypto = "^0.2"
